apiVersion: apps/v1
kind: Deployment

metadata:
  name: common-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: common-app

  template:
    metadata:
      labels:
        app: common-app

    spec:
      containers:
      - name: common-app
        image: daisuke8076/common-app:1.0.4
        ports:
        - containerPort: 80
